#!/usr/bin/env ruby
# -*- ruby -*-
#
#           Lens - Mail filtering utility for Maildir
#
# Copyright (C) 2004 Toshiyuki MASUI <masui@pitecan.com>
#
# $Id: lens,v 1.5 2004/02/17 08:36:53 masui Exp $
#
# This program 'Towers of Hanoi by TeX' is free software; you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation; either
# version 2 or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

require 'lens/lens'

LENSCONFIG = "#{ENV['HOME']}/.lensrc"
CMDCONFIG = "#{ENV['HOME']}/.commandmailrc"

if File.exist?(LENSCONFIG) then
  load LENSCONFIG
else
  puts "Config file <#{LENSCONFIG}> is missing."
  exit
end

if File.exist?(CMDCONFIG) then
  load CMDCONFIG
end

Lens.new(LensConfig,ARGV[0]).process
